// Copyright (c) Microsoft. All rights reserved.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Azure.AI.Projects;
using Microsoft.SemanticKernel.Agents.AzureAI.Internal;
using Microsoft.SemanticKernel.Agents.Memory;
using Microsoft.SemanticKernel.ChatCompletion;

namespace Microsoft.SemanticKernel.Agents.AzureAI;

public class AzureAIAgentChatThread : ChatThread
{
    private bool _threadActive = false;
    private string? _threadId = null;
    private readonly AgentsClient _client;

    public AzureAIAgentChatThread(AgentsClient client)
    {
        this._client = client;
    }

    /// <inheritdoc />
    public override bool HasActiveThread => this._threadActive;

    /// <inheritdoc />
    public override string? CurrentThreadId => this._threadId;

    /// <inheritdoc />
    public override async Task<string> StartNewThreadAsync(CancellationToken cancellationToken = default)
    {
        if (this._threadActive)
        {
            throw new InvalidOperationException("Thread already active.");
        }

        var assitantThreadResponse = await this._client.CreateThreadAsync(cancellationToken: cancellationToken).ConfigureAwait(false);
        this._threadId = assitantThreadResponse.Value.Id;
        this._threadActive = true;

        return assitantThreadResponse.Value.Id;
    }

    /// <inheritdoc />
    public override async Task EndThreadAsync(CancellationToken cancellationToken = default)
    {
        if (!this._threadActive)
        {
            throw new InvalidOperationException("No thread active.");
        }

        await this._client.DeleteThreadAsync(this._threadId, cancellationToken).ConfigureAwait(false);
        this._threadActive = false;
        this._threadId = null;
    }

    /// <inheritdoc />
    public override async Task OnNewMessageAsync(ChatMessageContent newMessage, CancellationToken cancellationToken = default)
    {
        if (!this._threadActive)
        {
            throw new InvalidOperationException("No thread active.");
        }

        // If the message was generated by this agent, it is already in the thread and we shouldn't add it again.
        if (newMessage.Metadata == null || !newMessage.Metadata.TryGetValue("ThreadId", out var messageThreadId) || !string.Equals(messageThreadId, this._threadId))
        {
            await AgentThreadActions.CreateMessageAsync(this._client, this._threadId!, newMessage, cancellationToken).ConfigureAwait(false);
        }
    }

    /// <inheritdoc />
    public override async Task<ChatHistory> RetrieveCurrentChatHistoryAsync(CancellationToken cancellationToken = default)
    {
        if (!this._threadActive)
        {
            throw new InvalidOperationException("No thread active.");
        }

        return new ChatHistory(await AgentThreadActions.GetMessagesAsync(this._client, this._threadId!, cancellationToken).ToListAsync(cancellationToken).ConfigureAwait(false));
    }
}
